Resources:
  MemeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:deployVariables.bucketName}
  MemeTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ${self:deployVariables.snsTopicName}
  MemeQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: ${self:service}-request-${self:provider.stage}
