---
local:
  bucketName: bsdc-2018-memegen-local
  snsTopicName: ${self:service}-request-topic-${self:provider.stage}
  snsTopicArn: arn:aws:sns:us-east-1:123456789012:${self:deployVariables.snsTopicName}
  sqsQueueUrl: http://localhost:4576/queue/local-memes-queue

develop:
  bucketName: bsdc-2018-memegen-local-develop
  snsTopicName: ${self:service}-request-topic-${self:provider.stage}
  snsTopicArn:
    'Ref': MemeTopic
  sqsQueueUrl:
    'Ref': MemeQueue

production:
  bucketName: bsdc-2018-memegen-production
  snsTopicName: ${self:service}-request-topic-${self:provider.stage}
  snsTopicArn:
    'Ref': MemeTopic
  sqsQueueUrl:
    'Ref': MemeQueue
