---
default:
  AWS_USE_SSL: true
  S3_BUCKET: ${self:deployVariables.bucketName}
  SNS_TOPIC: ${self:deployVariables.snsTopicArn}
  SQS_QUEUE_URL: ${self:deployVariables.sqsQueueUrl}

local:
  AWS_USE_SSL: false
  S3_FORCE_PATH_STYLE: true
  SNS_ENDPOINT: http://localhost:4575
  SQS_ENDPOINT: http://localhost:4576
  S3_ENDPOINT: http://localhost:4572
