service: bsdc-2018-memegen

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  timeout: 10

functions:
  createMeme:
    handler: handler.createMeme
    events:
      - http:
          path: meme
          method: get
