service: bsdc-2018-memegen

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  role: arn:aws:iam::770772978315:role/bsdc-2018-memegen-lambda
  memorySize: 128
  timeout: 10

functions:
  createMeme:
    handler: handler.createMeme
    events:
      - http:
          path: meme
          method: post

  sendMeme:
    handler: handler.sendMeme
    events:
      - sns: arn:aws:sns:us-east-1:770772978315:static-meme-topic

